name: 'picard-enterprise'

x-postgres: &postgres
  image: postgres:latest
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: postgres

services:
  picard-enterprise-postgres:
    <<: *postgres
    ports:
      - "5432:5432"

  picard-enterprise-planet-tracker-app:
    image: violabs/enterprise-planet-tracker:0.0.2-SNAPSHOT
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: picard-enterprise-postgres
      POSTGRES_DB: postgres
    ports:
      - "8080:8080"
